### ISSUE TITLE
Is it possible to pack dll files and *.dna to xll?

### ISSUE THREAD

**Issue by gagmeng** [caioproiete/ExcelDnaUnpack#1]
Is it possible to pack dll files and *.dna to xll?

Thanks.

**Comment by caioproiete** [comment]
If you are building an Excel Add-In with Excel-DNA using a class library with Visual Studio, then the `.dll` files as well as the `.dna` files will be automatically packed into the `.xll` during the build after you install the [`ExcelDna.AddIn` nuget package](https://www.nuget.org/packages/ExcelDna.AddIn/).

If you're not using Visual Studio, then you can manually do the packing by using the [`ExcelDnaPack.exe`](https://github.com/Excel-DNA/ExcelDna/tree/master/Distribution).

**Comment by gagmeng** [comment]
I recorded a video recording of my operation process, the video file is as follows：
https://mega.nz/#!bBhmFAzS!vRuyQtnXaAFqke6geE7a26x1LHt1GZv6AHNph_EJItw

The xll files used in the video are as follows:
https://mega.nz/#!2cwhjarA!qOIIpU77QenPKxc-BHs95UBkA6bUjWqRgq8PK4aMj1Y
https://mega.nz/#!7c41XQqZ!92ibujOQmsrcn6tTavhWA1eIVLEDCEIEqA5wJ0ZI5k8

Thank you for your kind guidance.
Best regards,
gagmeng

**Comment by gagmeng** [comment]
I recorded a video recording of my operation process, the video file is as follows：

The xll files used in the video are as follows:



Thank you for your kind guidance.
Best regards,
gagmeng

**Comment by gagmeng** [comment]
I recorded a video recording of my operation process, the video file is as follows：
https://mega.nz/#!bBhmFAzS!vRuyQtnXaAFqke6geE7a26x1LHt1GZv6AHNph_EJItw

The xll files used in the video are as follows:
https://mega.nz/#!2cwhjarA!qOIIpU77QenPKxc-BHs95UBkA6bUjWqRgq8PK4aMj1Y
https://mega.nz/#!7c41XQqZ!92ibujOQmsrcn6tTavhWA1eIVLEDCEIEqA5wJ0ZI5k8

Thank you for your kind guidance.
Best regards,
gagmeng

**Comment by gagmeng** [comment]
Solve it, Thanks.
